
---
- hosts: all
  tasks:
   - name: print fact variable values
     debug:
      msg:
       - " the os distribution is : {{ansible_distribution}}"
       - " the os name is : {{ansible_system}}"
       - " the os family is : {{ansible_os_family}}"
